apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:gZEkP7egun+CshX73ud+KuUD+08hqWYXl2UEwjivgctvMEJLxxqjMg==,iv:enRm1ZkR3WY4e9+qJFFsM82rfAYqPEw/NuaxjozCyfU=,tag:O4RHMwekS4w4QXP+bB8NcA==,type:str]
sops:
  age:
    - recipient: age1p78cjrhn3wdsc7zluwhnmhauf7lzp32v9l8fn2qkk5sczg70yqqsunu4jx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFIxWmo2TTNIcE5FZTl4
        N3BZVUhSMVNwVUl5ZGNmbTFYcGZ5ODh6Um5NCnZJSHp1bXVoQndmaVZxTFVHME91
        SkY3Zm1Pa2k3U0NBTldFczFpWkR5R1kKLS0tIGxFcmZEUDErRlhjbkovWEF6TGM1
        YmtjWGkzYjM2aS9DalF6TmJFRS9sMDAKjCoQ9CZNUcPbyJ24DIDdTHrupmzV/i4V
        keLMLQ8ogciYHq++R+ncky0Nl7cy8HEkPrMYXp4oJkEznfdgSIKK4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:17:27Z"
  mac: ENC[AES256_GCM,data:OYQ4m6hv9JlAaKvNdPGrGM++4cUSoh/qoS/+/1EAdeqIPGZSs4H4L3WXiliGUQ4pWZQq6y7WXyMiDBRi2rhWjXoiy26u0fh7RnoWD4YVfX7ZXQRXSRIfBdETKK/fbTe16x5zq88Q7d/AdrPwHHHKeMMcJaU1on/yZhpnXzX4CQY=,iv:gj6U2S5/pqFwsvvWiPpUFuwy8ETNbtPv0XXQypYyobE=,tag:5ke964YIUFFaVvTNR6oEqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
