apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XQnhVjsiDE0=,iv:ts/tUres7XhcNF1mwxvJ9YogkqgmProKE/0X7nCEEc0=,tag:bXfGBVfTmftgt8zNs9W19w==,type:str]
sops:
  age:
    - recipient: age1p78cjrhn3wdsc7zluwhnmhauf7lzp32v9l8fn2qkk5sczg70yqqsunu4jx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL05PS2xrUDBuTG55Z0h2
        SEFpa0dRb3dIVk16ZHRPQzcrQlE5ZzRUazIwCjJPZHhjbkpDQTIzd1UyZ1I4aWpp
        Q3Rqc212M21rQUdZcU1OV05BZUhacmcKLS0tIDRBdHJtQlNBclY5R1BIVUJxOXZK
        MXNqSTNIRkVNOVpFV3U0SVNaTkQ3ekkKo+PbRAHr65eGvf3dWf5Xt0p9iCxr3pGG
        OJPL66+K3TtlmP1thzwWPNpvJTgMDwmTFIlNIGnsedxhSCzf3mgB+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:17:27Z"
  mac: ENC[AES256_GCM,data:S4jAK9SkOFra2tKJtRf0e/I4fGdZiQj8EAXWvJUoEM06EU+9Sb5YfymppputQ4MnC8ttfgYogMtHtun3NS4CpdGW1Lo6Kok48BxERK8vxeoiiLZr2aU/XW85moZMAhhBtgfLiOFbOnZwZ/sjW4vg8qk7TJLc/B5+Z10pz8pOH9I=,iv:6+0asLF4vs1CGaZDBEnHn5POiQ9xdjozj4CYsEdB2Gs=,tag:XtEMzb2k7227a/ULD/7jSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
