apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:juV2oAom9qS6uiszEIFjbuxyhfa1kHM9y66jU9FDdA8=,iv:t3Wlv6SzzYp5rbN4PwzGfxXgfYUTW0JOh2BcPgNc3bQ=,tag:BHJf21u5psB85kjC4xW11g==,type:str]
sops:
  age:
    - recipient: age1p78cjrhn3wdsc7zluwhnmhauf7lzp32v9l8fn2qkk5sczg70yqqsunu4jx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OTVuam5qOE9QZXBWc1VS
        YXRqQyt4MUJGUENBUVJ0L3pWWjI2a2t5Y3dvCkJOMEdwRHNURzJLRGliMWVRNnRp
        cDVnYWZVY3FwRm5HR29KOUZhSllWMVkKLS0tIFFUZlJINWRVdWJNSlBSVEZjN1dF
        d1BqMjJBdWRxbzFUTEJHalc5enBEc00K3B5nCq6e64NzpI7b2anesc5C9LrCHqWY
        s4qgmKNfyx+qos5bEJcmj8N6fTkQ+xf/9RHq978Ifx1DHgxL7AQf6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:17:27Z"
  mac: ENC[AES256_GCM,data:GO09zP2WgdKbVZaQUA8oTUQy+VirBRJGUhs8ZHiLu/wUuCoj9UA0gZGtE3bRia10p2kp+rtszYOVzRih8agwqZWiaWExHhYT1fD4wMk64lQkTYqry7THjbMJxWDsc1m4V4v3gqzoXqlS1dYqU3fJ+oE79fVxmYXeYcTgopQQ95k=,iv:DolwkzW769OJlN/GdEVd2RBuVOZnUUp5OxNJJC9r2Go=,tag:M0trhTuO+cjHLg9pWjlmdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
