apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LK51RKLYXmItK8eUO9npHHTRdUqISuIrSUZi47z2vpWXyjzYNF7E5Xt+Q6FJuvWyMlHxMl9JwVuowr1ZZZ4kru7ec4oWY7xTlH8xCyrZF69lC8hPWH38IbJuGdtJNB327PnnaicwlMH64vwXL5bLa90MKITQvwIa6EepJ8aAZk8zOYiuPguntFS4amylMd9FDur0Q5MIwQY9nJeDNDPamCqtKkZt6BhqzlbYxFJUtxl1imLq,iv:siipol9epyvY78AaHAjBh5TceErVNs2+MQAi7HNHlxM=,tag:8N69ReTHMasY3v6KmCEOjg==,type:str]
sops:
  age:
    - recipient: age1p78cjrhn3wdsc7zluwhnmhauf7lzp32v9l8fn2qkk5sczg70yqqsunu4jx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSmtJSkVwOWpGcWxJdTJU
        eXJsbUUya3o3WTNmZFJYeVowbHBYSWF6aFN3CkYrSVltMjlmNUJIYzhUemhCUnVX
        blQ5QjcvOXYyQVdrVGJkdllBYlFXaWcKLS0tIG5VUVZpSlAyaE9UNWdYMFFLKzR4
        RDFYL1VRUTdPeGhvS0hjZkhSdi9vU1EKfxvfaGqjAAWTwRTMCzolgiSqCe2M+OIT
        dOuzlAAN46sZLv/AYZmWZIRD502IDBTC1pzAx4neUGtbkqFj0K/MSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:17:27Z"
  mac: ENC[AES256_GCM,data:mRPaGEFo2T8QGfqlM0Q8Fox+gJCafMzascenvZTop8GlAyaDFglTnWygC36l3Da+PKvQQ1QFQBNUz4K38SVlYjA4jtw3EWmQONokpsddao6EotETiLyi54PjT05uc07k5eCGjks3pMFQ3ibjUoOv0EBToqZPMfH5EhtE020ATKk=,iv:5dzX8jj3yMV49VYUlfnt2WC+drCE4FzUQfbUA8k7NyE=,tag:Mdc7PW5ueAKLJcZPMBdpFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
