apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:M5D8GSN+G12VoSzjYIM/ctXqxzrL9HAZ7bioRn+byZctU8nOH6B4Bg==,iv:LWw3sfej4QQuy28lIEVr0HVFUh+TfIC83Jcbv9Hzmy0=,tag:Rn6y1ID7epkMnh0Rj6atOQ==,type:str]
sops:
  age:
    - recipient: age1p78cjrhn3wdsc7zluwhnmhauf7lzp32v9l8fn2qkk5sczg70yqqsunu4jx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQXJERzRHcnVvdHllMVFs
        dGd0YzBEc0grcFFWakJDUFIvY0YxSzRRQlRjCld0WHhZUDF6RFFYY0JRNTRJVzV3
        djJMTFlod2JKZmM4dCtmaE4vV01NSWMKLS0tIHlhaTVHUDhaZEVReUlSamJtRVdZ
        eGQ4c3VWLzVpWXRDN2R2Yld6WU0yMFkKgvwDjLQmnjH0LweuOZ+jMzy+aYnoXAWq
        9oNro/AcXWRwEwuIrPGc9hxnqwIgbMjf+g0wYKUuUjoEawtZxdY2+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:17:27Z"
  mac: ENC[AES256_GCM,data:SHA0KS1oC3I2nik1kyrX3+1aIfkc4vAMr4Q+Je/lOEhKINwqj/htaFj+MvNMwHBEa/mP8wtZUmzGuivF0DGSIy5s+xAMDhb5IDbY4+UBVCht19twpgcXvYG4kvLgL6+K/U+Oy0P5aP4Pzgim6A77f1Uq8mkEHfYfR2IVwxyNnso=,iv:02cXU1gG0BpZ1ngGoc84FHvcEkK/kzV26CiqnRw8fI8=,tag:9RuMwQ2H/Iwa8DeBYFHEEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
