---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - name: http
      port: 3005
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: gitea-1
  labels:
    kubernetes.io/service-name: gitea
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 3005
endpoints:
  - addresses:
      - 192.168.3.5
